# Generated by Django 5.1.6 on 2025-03-01 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='ticket_type',
            new_name='ticket_price',
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'ticket_price')},
        ),
    ]
