# Generated by Django 5.1.6 on 2025-04-04 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketprice',
            name='name',
            field=models.CharField(choices=[('Ordinary', 'Ordinary'), ('Near_Stage', 'Near Stage'), ('VIP', 'VIP'), ('VVIP', 'VVIP')], max_length=50),
        ),
    ]
