# Generated by Django 5.1.6 on 2025-04-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_ticketprice_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
