# Generated by Django 5.1.6 on 2025-03-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_rename_ticket_type_cartitem_ticket_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='price',
        ),
    ]
