# Generated by Django 5.1.6 on 2025-04-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticket_ticket_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('concert', 'Concert'), ('party', 'Party'), ('conference', 'Conference'), ('sports', 'Sports'), ('theatre', 'Theatre')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticketprice',
            name='name',
            field=models.CharField(choices=[('rdinary', 'Ordinary'), ('near_stage', 'Near Stage'), ('vip', 'VIP'), ('vvip', 'VVIP')], max_length=50),
        ),
    ]
