# Generated by Django 5.1.6 on 2025-04-03 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
    ]
