# Generated by Django 5.1.6 on 2025-02-24 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='phone_number',
            field=models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Enter a valid 9-digit phone number.', regex='^\\d{9}$')]),
        ),
    ]
