# Generated by Django 5.1.6 on 2025-03-10 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_ticket_ticket_price'),
        ('payment', '0002_alter_payment_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicefee',
            name='ticket_price',
            field=models.ForeignKey(default=0.0, on_delete=django.db.models.deletion.CASCADE, to='events.ticketprice'),
        ),
    ]
