# Generated by Django 5.1.6 on 2025-02-27 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payment', '0005_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.event'),
        ),
    ]
