# Generated by Django 5.1.6 on 2025-02-27 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('payment', '0006_alter_payment_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=5.0, max_digits=10)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_fee', to='events.event')),
            ],
        ),
    ]
